### ISSUE TITLE
Missing Curse.Desktop.exe

### ISSUE THREAD

**Issue by PhilSkinn** [kaeedo/Cursed#9]
I was using this, trying to download Project Ozone from curse and I tried launching this and it crashed my computer entirely. I'm not sure if I tried launching the wrong thing. I tried doing what the main page did (the one with the files listed) and launching "Cursed.Desktop.exe" but I could not find it anywhere. I launched something called paket.bootstrapper. I know I shouldn't have, but doing that immediately crashed my computer and it refused to restart... I'm still looking for the Cursed.Desktop.exe, but it's still nowhere to be found. I'm not mad at anyone but myself for doing that and so I apologize for making this your problem. I'll keep looking and do some research on where it might be located/renamed. I'll also use a different modpack downloader. I would appreciate some assistance as soon as you can get around to it.

**Comment by kaeedo** [comment]
Hi.

I'm assuming you're on Windows. It looks like you downloaded the source code instead of the compiled program. You can find that under the Releases tab here: https://github.com/kaeedo/Cursed/releases
I suggest grabbing the latest version zip file: https://github.com/kaeedo/Cursed/releases/download/v1.4.1/Cursed_1.4.1.zip
